version: '3.8'

services:
  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    volumes:
      - ../:/app
    environment:
      - PYTHONPATH=/app
    command: pytest -xvs tests/