version: '3.8'

services:
  recsys-lite-simple-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.simple
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped