version: '3.8'

services:
  recsys-lite:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../data:/data
      - ../model_artifacts:/app/model_artifacts
    ports:
      - "8000:8000"
    environment:
      - DB_PATH=/data/recsys.db
      - MODEL_PATH=/app/model_artifacts
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped