name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3-dev libopenblas-dev
    
    - name: Set up Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.5.1
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    
    - name: Install dependencies with pip
      run: |
        python -m pip install --upgrade pip
        python -m pip install mypy ruff black isort pytest pytest-cov scipy numpy
        # Install LightFM directly from pip before other packages
        # Set environment variable to help LightFM build
        LIGHTFM_NO_CFLAGS=1 python -m pip install lightfm==1.16
        # Continue with remaining dependencies via pip first
        python -m pip install -e .
    
    - name: Lint with ruff
      run: |
        python -m ruff .
    
    - name: Type check with mypy
      run: |
        python -m mypy --ignore-missing-imports src
    
    - name: Format check with black
      run: |
        python -m black --check src
    
    - name: Run tests
      run: |
        python -m pytest --cov=src tests/

  docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker/Dockerfile
        push: false
        tags: recsys-lite:latest
        outputs: type=docker,dest=/tmp/recsys-lite.tar
    
    - name: Check image size
      run: |
        docker load --input /tmp/recsys-lite.tar
        SIZE=$(docker images recsys-lite:latest --format "{{.Size}}")
        echo "Image size: $SIZE"
        # Check if image size is less than 1GB
        if [[ $SIZE == *GB ]]; then
          GB_VALUE=$(echo $SIZE | sed 's/GB//')
          if (( $(echo "$GB_VALUE > 1" | bc -l) )); then
            echo "Image size exceeds 1GB: $SIZE"
            exit 1
          fi
        fi
    
    - name: Generate SBOM with Syft
      uses: anchore/sbom-action@v0
      with:
        image: recsys-lite:latest
        artifact-name: recsys-lite-sbom
        output-file: ./sbom.json