name: CI
  
permissions:
  contents: read
  actions: write

on:
  push: {}
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Ruff auto-fix
        run: |
          poetry run ruff check src --fix
          poetry run ruff format src
      - name: Ruff lint
        run: poetry run ruff src              # fails only on new issues
      - name: Type-check with mypy
        run: poetry run mypy --strict src
      - name: Run tests and capture logs
        run: |
          mkdir -p artifacts logs
          set -o pipefail
          poetry run pytest --maxfail=1 --disable-warnings -q --junitxml=artifacts/test-results.xml 2>&1 | tee logs/test-output.log

      - name: Upload test results artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: artifacts/test-results.xml

      - name: Upload workflow logs artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: workflow-logs
          path: logs/test-output.log

  docker-build:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -f docker/Dockerfile -t recsys-lite:latest .
      - name: Check Docker image size
        run: |
          IMAGE_SIZE=$(docker image inspect recsys-lite:latest --format='{{.Size}}')
          echo "Image size: $IMAGE_SIZE bytes"
      - name: Generate SBOM with Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          syft recsys-lite:latest -o json > sbom.json
      - name: Security scan with Trivy
        uses: aquasecurity/trivy-action@v0.12.0
        with:
          image-ref: recsys-lite:latest
          format: 'table'
          severity: HIGH,CRITICAL